name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main

env:
  POETRY_VERSION: "1.8.3"

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} ${{matrix.os}}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: ["windows-latest", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install poetry
        shell: bash
        run: |
          pip install "poetry==$POETRY_VERSION"
          poetry --version

      - name: Install dependencies
        shell: bash
        run: |
          poetry install --with test

      - name: Run tests
        shell: bash
        run: |
          poetry run pytest
